version: "3.7"
services:
  db:
    container_name: perrymason
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: Stuttering
      POSTGRES_PASSWORD: Bishop
    ports:
      - 5434:5432
    volumes:
      - ./postgres:/var/lib/postgresql/perrymason
      
  