version: "3.7"
services:
  db:
    container_name: dumbo
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: Dumbo
      POSTGRES_PASSWORD: Elefante
    ports:
      - 5435:5432
    volumes:
      - ./postgres:/var/lib/postgresql/dumbo
      
  